default_location: Singapore
locations:
  Singapore:
    lat: 1.3521
    lon: 103.8198
    timezone: Asia/Singapore
  Perth:
    lat: -31.9522
    lon: 115.8614
    timezone: Australia/Perth
  Bad Fischau:
    lat: 47.83137
    lon: 16.16707
    timezone: Europe/Vienna
objects:
  - Object: M42
    Name: "Orion Nebula"
    Type:
    Project:
  - Object: "NGC 7000"
    Name: "North America Nebula"
    Type:
    Project:
  - Object: "NGC 3372"
    Name: "Carina Nebula"
    Type:
    Project:
  - Object: "NGC 2170"
    Name: "Angel Nebula"
    Type:
    Project: plan to take with hyperstar
  - Object: "NGC 6334"
    Name: "Cat's Paw Nebula"
    Type:
    Project:
  - Object: M45
    Name: Pleiades
    Type:
    Project:
  - Object: M78
    Name: "Caspar the friendly Ghost"
    Type:
    Project:
  - Object: "IC 443"
    Name: "Jellyfish Nebula"
    Type:
    Project:
  - Object: "NGC 2070"
    Name: "Tarantula Nebula"
    Type:
    Project:
  - Object: "NGC 7293"
    Name: "Helix Nebula"
    Type:
    Project:
  - Object: "NGC 5139"
    Name: "Omega Centauri"
    Type:
    Project:
  - Object: "NGC 5128"
    Name: "Centaurus A"
    Type:
    Project:
  - Object: M16
    Name: "Eagle Nebula"
    Type:
    Project:
  - Object: "NGC 1365"
    Name: "Great Barred Spiral Galaxy"
    Type:
    Project:
  - Object: M51
    Name: "Whirlpool Galaxy"
    Type:
    Project:
  - Object: "NGC 2359"
    Name: "Thors Helmet"
    Type:
    Project:
  - Object: "IC 4604"
    Name: "Rho Ophiuchi"
    Type:
    Project:
  - Object: "TGU H1867"
    Name: "Coalsack Nebula"
    Type:
    Project:
  - Object: "LDN 1295"
    Name: "Giraffe Nebula"
    Type:
    Project:
  - Object: "NGC 292"
    Name: "Small Magellanic Cloud"
    Type:
    Project:
  - Object: "NGC 869/884"
    Name: "Double Cluster"
    Type:
    Project:
  - Object: "IC 2602"
    Name: "Southern Pleiades"
    Type:
    Project:
  - Object: "NGC 2392"
    Name: "Eskimo Nebula"
    Type:
    Project:
  - Object: M31
    Name: "Andromeda Galaxy"
    Type:
    Project:
  - Object: M57
    Name: "Ring Nebula"
    Type:
    Project:
  - Object: "NGC 6543"
    Name: "Cats Eye Nebula"
    Type:
    Project:
  - Object: M97
    Name: "Owl Nebula"
    Type:
    Project:
  - Object: "NGC 7331"
    Name: "NGC 7331 & Stephans Quintet"
    Type:
    Project:
  - Object: M106
    Name: "Spiral galaxy in the constellation Canes Venatici"
    Type:
    Project:
  - Object: "NGC 7635"
    Name: "Bubble Nebula"
    Type:
    Project:
  - Object: "NGC 891"
    Name: "Silver Sliver galaxy"
    Type:
    Project:
  - Object: LMC
    Name: "Large Magellanic Cloud"
    Type:
    Project:
  - Object: "NGC 4755"
    Name: "Jewel Box Cluster"
    Type:
    Project:
  - Object: "NGC 3338"
    Name: "Rosette Nebula"
    Type:
    Project:
  - Object: M13
    Name: "Hercules Cluster"
    Type:
    Project:
  - Object: M104
    Name: "Sombrero galaxy"
    Type:
    Project:
  - Object: "NGC 5985"
    Name: "Leo Triplet"
    Type:
    Project:
  - Object: "NGC 6960"
    Name: "Veil Nebula"
    Type:
    Project:
  - Object: "IC 1396"
    Name: "Elephant Trunk Nebula"
    Type:
    Project:
  - Object: "NGC 6888"
    Name: "Crescent Nebula"
    Type:
    Project:
  - Object: M27
    Name: "Dumbbell Nebula"
    Type:
    Project:
  - Object: "NGC 7023"
    Name: "Iris Nebula"
    Type:
    Project:
  - Object: "NGC 7380"
    Name: "Wizard Nebula"
    Type:
    Project:
  - Object: M33
    Name: "Triangulum galaxy"
    Type:
    Project:
  - Object: "IC 5146"
    Name: "Cocoon Nebula"
    Type:
    Project:
  - Object: M82
    Name: "Cigar galaxy"
    Type:
    Project:
  - Object: "PN ARO 121"
    Name: "Jones-Emberson 1"
    Type:
    Project:
